version: '3.8'

services:
  web:
    build: .
    container_name: petstore
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
        - "5432:5432"