version: '3.8'

services:
  web:
    build: .
    container_name: petstore
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - my_network
  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
        - "5432:5432"
    restart: unless-stopped
    networks:
       - my_network    
volumes:
  pg-data:
networks:
  my_network:
    driver: bridge