DROP TABLE IF EXISTS pets;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS token_blacklist;
DROP INDEX IF EXISTS idx_token_blacklist_expires;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS pet_tags;